stages:
  - build
  - test

image: montavont/algodesreseaux

build_04:
  stage: build
  script:
    - cd 04-affichage-adresse
    - scons
  artifacts:
    paths:
      - 04-affichage-adresse/receiver-udp

# run tests using the binary build before
test_04:
  stage: test
  needs: [build_04]
  script:
  - |
    echo "starting tests"
    cd 04-affichage-adresse
    bash tests.sh
