stages:
  - build
  - test

image: montavont/algodesreseaux

build_05:
  stage: build
  script:
    - cd 05-emetteurUDPv6
    - scons
  artifacts:
    paths:
      - 05-emetteurUDPv6/sender-udp

# run tests using the binary build before
test_05:
  stage: test
  needs: [build_05]
  script:
  - |
    echo "starting test"
    cd 05-emetteurUDPv6
    bash tests.sh
