stages:
  - build
  - test

image: montavont/algodesreseaux

build_09:
  stage: build
  script:
    - cd 09-transfert-fichierTCPv6-source
    - scons
  artifacts:
    paths:
      - 09-transfert-fichierTCPv6-source/sender-tcp

# run tests using the binary build before
test_09:
  stage: test
  needs: [build_09]
  script:
  - |
    echo "starting tests"
    cd 09-transfert-fichierTCPv6-source
    bash tests.sh
