stages:
  - build
  - test

image: montavont/algodesreseaux

build_02:
  stage: build
  script:
    - cd 02-config-adresse
    - scons
  artifacts:
    paths:
      - 02-config-adresse/sender-udp

# run tests using the binary build before
test_02:
  stage: test
  needs: [build_02]
  script:
  - |
    echo "starting test"
    cd 02-config-adresse
    bash tests.sh
